<h3>Import Libraries</h3>

In [3]:
import pandas as pd
import numpy as np

<h3>Load Dataset</h3>

In [5]:
# read telco-customer-churn dataset
df = pd.read_csv(r"C:\Users\kalpa\Downloads\Puneri Pattern_DA all notes\Telco-Customer-Churn Dataset.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [7]:
# Display first 5 rows
print(df.head())

   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No
1  5575-GNVDE    Male              0      No         No      34          Yes
2  3668-QPYBK    Male              0      No         No       2          Yes
3  7795-CFOCW    Male              0      No         No      45           No
4  9237-HQITU  Female              0      No         No       2          Yes

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No
1                No             DSL            Yes  ...              Yes
2                No             DSL            Yes  ...               No
3  No phone service             DSL            Yes  ...              Yes
4                No     Fiber optic             No  ...               No

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes
1          No          No              No        One year               No
2          No          No              No  Month-to-month              Yes
3         Yes          No              No        One year               No
4          No          No              No  Month-to-month              Yes

               PaymentMethod MonthlyCharges  TotalCharges Churn
0           Electronic check          29.85         29.85    No
1               Mailed check          56.95        1889.5    No
2               Mailed check          53.85        108.15   Yes
3  Bank transfer (automatic)          42.30       1840.75    No
4           Electronic check          70.70        151.65   Yes

[5 rows x 21 columns]

In [8]:
# Dispaly Last 5 rows
print(df.tail())

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
7038              Yes               Mailed check          84.80        1990.5
7039              Yes    Credit card (automatic)         103.20        7362.9
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40         306.6
7042              Yes  Bank transfer (automatic)         105.65        6844.5

     Churn
7038    No
7039    No
7040    No
7041   Yes
7042    No

[5 rows x 21 columns]

<h3>Understand Dataset</h3>

In [11]:
# Check number of rows and columns
print("Shape of dataset:",df.shape)

Shape of dataset: (7043, 21)

In [12]:
# Dispaly column names
print("Columns:",df.columns)

Columns: Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [13]:
# Information about data types and missing values
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB
None

<h3>Data Cleaning</h3>

In [15]:
# Check missing values in each column

print("Missing Values:\n",df.isnull().sum())

Missing Values:
 customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [40]:
# Convert 'TotalCharges' column to numeric (it may contain text/blank values)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [41]:
# fill missing values
df.fillna(df.mean(numeric_only=True), inplace=True)

In [42]:
# check duplicate rows 
print("Duplicate rows:",df.duplicated().sum())

Duplicate rows: 0

In [43]:
# remove duplicates if any
df = df.drop_duplicates()

In [44]:
# Handle incorrect values

# Check unique value in categorical columns
print(df["Contract"].unique())

['Month-to-month' 'One year' 'Two year']

In [45]:
print(df["PaymentMethod"].unique())

['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

<h3>Basic Churn Analysis</h3>

In [46]:
# Count how many customers churned and how many stayed
print("Churn count:\n", df['Churn'].value_counts())

Churn count:
 Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [22]:
# Churn Percentage
print("Churn percentage:\n",df["Churn"].value_counts(normalize=True)*100)

Churn percentage:
 Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

<h3>Exploratory Data Analysis (EDA)</h3>

In [47]:
# Contract vs Churn
# analyze churn based on contract type
print("Contract vs Churn:\n", df.groupby("Contract")["Churn"].value_counts(normalize=True))

Contract vs Churn:
 Contract        Churn
Month-to-month  No       0.572903
                Yes      0.427097
One year        No       0.887305
                Yes      0.112695
Two year        No       0.971681
                Yes      0.028319
Name: proportion, dtype: float64

In [48]:
# Tenure vs Churn
# Compare average tenure of churned vs non-churned customers
print("Average tenure:\n",df.groupby("Churn")["tenure"].mean())

Average tenure:
 Churn
No     37.569965
Yes    17.979133
Name: tenure, dtype: float64

In [49]:
# Monthly Charges vs Churn
# Compare average monthly charges
print("Average Monthly Charges:\n",
      df.groupby('Churn')['MonthlyCharges'].mean())

Average Monthly Charges:
 Churn
No     61.265124
Yes    74.441332
Name: MonthlyCharges, dtype: float64

In [50]:
# Payment method vs Churn
# Analyze churn by payment method
print("Payment method vs Churn:\n",
      df.groupby("PaymentMethod")["Churn"].value_counts(normalize=True))

Payment method vs Churn:
 PaymentMethod              Churn
Bank transfer (automatic)  No       0.832902
                           Yes      0.167098
Credit card (automatic)    No       0.847569
                           Yes      0.152431
Electronic check           No       0.547146
                           Yes      0.452854
Mailed check               No       0.808933
                           Yes      0.191067
Name: proportion, dtype: float64

<h4>High Risk Customers</h4>

In [51]:
# High charges + low tenure = high risk
# create new column "HighRisk"
df['HighRisk'] = np.where(
    (df['MonthlyCharges'] > 70) & (df['tenure'] < 12),
    'Yes', # High risk
    'No'   # Low risk
)

# Display data with new column
df[['MonthlyCharges','tenure','HighRisk']].head()

   MonthlyCharges  tenure HighRisk
0           29.85       1       No
1           56.95      34       No
2           53.85       2       No
3           42.30      45       No
4           70.70       2      Yes

<h4>Long Term Customers</h4>

In [52]:
df["LongTermCust"]= np.where(
    df['tenure']>24,
    "Yes","No"
)

df[['tenure','LongTermCust']].head()

   tenure LongTermCust
0       1           No
1      34          Yes
2       2           No
3      45          Yes
4       2           No

<h4>Customer Value</h4>

In [56]:
# Customer Value based on Total Charges
df['CustomerValue'] = np.where(
    df['TotalCharges'] > df['TotalCharges'].median(),
    'High', 'Low'
)

df[['TotalCharges','CustomerValue']].head()

   TotalCharges CustomerValue
0         29.85           Low
1       1889.50          High
2        108.15           Low
3       1840.75          High
4        151.65           Low

In [59]:
# Create tenure groups
df['tenure_group'] = pd.cut(
    df['tenure'],
    bins=[0,12,24,36,48,60,72],
    labels=['0-1 yr','1-2 yr','2-3 yr','3-4 yr','4-5 yr','5-6 yr']
)

df[['tenure','tenure_group']].head()

   tenure tenure_group
0       1       0-1 yr
1      34       2-3 yr
2       2       0-1 yr
3      45       3-4 yr
4       2       0-1 yr

In [60]:
print("\nFinal Insights:")
print("1. Month-to-month contract customers have higher churn.")
print("2. Customers with low tenure are more likely to leave.")
print("3. Higher monthly charges increase churn.")
print("4. High-risk customers identified using business logic.")

Final Insights:
1. Month-to-month contract customers have higher churn.
2. Customers with low tenure are more likely to leave.
3. Higher monthly charges increase churn.
4. High-risk customers identified using business logic.

In [61]:
# Save Dataset 
df.to_csv("Cleaned_Churn_data.csv",index=False)